### ISSUE TITLE
subset samples by # of reads step omitted from dada2 vis script

### ISSUE THREAD

**Issue by sydneygreenlee** [BigelowLab/edna-dada2#35]
I couldn't make a NMDS plot before filtering out low read # samples:

I ran the script verbatim and all variable names matched:

ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray") 

From ordinate() I got the error:

**Error in if (autotransform && xam > 50) { : missing value where TRUE/FALSE needed**

Filtering out samples with low (0, single-digit, and 10s of reads) solved this, code below (thanks Robin!):

ps_env <- ps %>%
  subset_samples(sample_sums(ps) > 500)  #change number to your preferred threshold

**Comment by btupper** [comment]
Oh my, @robinsleith where did this script come from?  What nightmare have you visited upon us? Help forthwith or when you can!

**Comment by robinsleith** [comment]
This little gremlin? This is just the handshake between the output from the pipeline and the [phyloseq](https://joey711.github.io/phyloseq/) package which we use for visualization and analysis. Just to set the record straight there is nothing omitted necessarily. The point of the script is to work with the toy dataset in the tutorial and for that dataset we do not need to filter by number of reads because all the samples have good numbers of reads. When people like Sydney use the script on their own data then things can fall apart without the filter she is referencing. So for the sake of other users in the future and out of the goodness of my heart I will add the step mentioned above.
